"""字幕导出模块 — SRT / ASS / 带时间戳纯文本"""

import os


# ── 时间戳格式化 ──────────────────────────────────────────────


def _format_srt(seconds: float) -> str:
    """SRT 时间戳: HH:MM:SS,mmm"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _format_ass(seconds: float) -> str:
    """ASS 时间戳: H:MM:SS.mmm"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    return f"{h}:{m:02d}:{s:02d}.{ms:03d}"


def _format_txt(seconds: float) -> str:
    """文本时间戳: [HH:MM:SS.mmm]"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    return f"[{h:02d}:{m:02d}:{s:02d}.{ms:03d}]"


# ── 写入函数 ──────────────────────────────────────────────────


def write_srt(segments: list[dict], filepath: str) -> str:
    """将 segments 写入 SRT 格式字幕文件。

    Args:
        segments: 每个元素为 {"start": float, "end": float, "text": str}
        filepath: 输出文件路径

    Returns:
        写入的文件路径 (与 filepath 相同)
    """
    lines: list[str] = []
    for idx, seg in enumerate(segments, start=1):
        start = _format_srt(seg["start"])
        end = _format_srt(seg["end"])
        lines.append(str(idx))
        lines.append(f"{start} --> {end}")
        lines.append(seg["text"].strip())
        lines.append("")

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


def write_ass(segments: list[dict], filepath: str) -> str:
    """将 segments 写入 ASS 格式字幕文件（基本样式）。

    Args:
        segments: 每个元素为 {"start": float, "end": float, "text": str}
        filepath: 输出文件路径

    Returns:
        写入的文件路径 (与 filepath 相同)
    """
    header = (
        "[Script Info]\n"
        "; Script generated by video-notes-ai\n"
        "ScriptType: v4.00+\n"
        "PlayResX: 384\n"
        "PlayResY: 288\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        "Style: Default,SimHei,20,&H00FFFFFF,&H000000FF,&H00000000,"
        "&H64000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, "
        "MarginV, Effect, Text\n"
    )

    lines: list[str] = [header]
    for seg in segments:
        start = _format_ass(seg["start"])
        end = _format_ass(seg["end"])
        text = seg["text"].strip()
        # ASS 中 {} 是样式覆盖标记，需要转义
        text = text.replace("{", "｛").replace("}", "｝")
        lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


def write_timestamped_txt(segments: list[dict], filepath: str) -> str:
    """写入带时间戳的纯文本。

    每行格式::

        [00:00:05.000 → 00:00:10.000] 文本内容

    Args:
        segments: 每个元素为 {"start": float, "end": float, "text": str}
        filepath: 输出文件路径

    Returns:
        写入的文件路径 (与 filepath 相同)
    """
    lines: list[str] = []
    for seg in segments:
        start = _format_txt(seg["start"])
        end = _format_txt(seg["end"])
        text = seg["text"].strip()
        lines.append(f"{start} → {end} {text}")

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath