"""Job metadata persistence port."""

from __future__ import annotations

from typing import Optional, Protocol

from src.domain.job_state import JobRecord, JobState


class JobMetadataStore(Protocol):
    def start_run(
        self,
        input_path: str,
        title: Optional[str] = None,
        job_dir: Optional[str] = None,
        job_id: Optional[str] = None,
        request_snapshot: dict | None = None,
        parent_run_id: int | None = None,
        attempt: int = 1,
    ) -> int: ...

    def update_progress(
        self,
        run_id: int,
        stage: JobState,
        progress: float,
        message: str = "",
    ) -> None: ...

    def complete_run(
        self,
        run_id: int,
        output_path: Optional[str] = None,
        transcript_path: Optional[str] = None,
        elapsed_sec: float = 0.0,
        frames_count: int = 0,
        blocks_count: int = 0,
        note_id: Optional[int] = None,
    ) -> None: ...

    def fail_run(self, run_id: int, error_message: str) -> None: ...
    def mark_interrupted_runs(self, reason: str) -> int: ...
    def request_stop(self, run_id: int, action: str) -> None: ...
    def pause_run(self, run_id: int) -> None: ...
    def cancel_run(self, run_id: int) -> None: ...
    def prepare_resume(self, run_id: int) -> bool: ...
    def detach_workspace(self, run_id: int) -> bool: ...
    def get_job(self, run_id: int) -> JobRecord | None: ...
    def get_job_by_job_id(self, job_id: str) -> JobRecord | None: ...

    def list_jobs(
        self,
        limit: int = 20,
        offset: int = 0,
        status: str | None = None,
        order_by: str = "started_at DESC",
    ) -> list[JobRecord]: ...

    def list_all_jobs(self, limit: int = 100000) -> list[JobRecord]: ...
    def count_jobs(self, status: str | None = None) -> int: ...
    def delete_run(self, run_id: int) -> bool: ...
    def delete_run_with_index(self, run_id: int, job_id: str) -> bool: ...
    def clear_all(self) -> int: ...
    def list_hidden_purge_candidates(self) -> list[dict]: ...
    def count_hidden_collection_jobs(self) -> int: ...
    def purge_hidden_runs(self, run_ids: list[int]) -> dict[str, int]: ...

