"""Provenance persistence port."""

from __future__ import annotations

from typing import Protocol


class ProvenanceStore(Protocol):
    def clear_job(self, job_id: str) -> None: ...

    def index_video_source(
        self,
        job_id: str,
        source_type: str,
        source_uri: str,
        title: str | None,
        duration: float | None,
        local_video_path: str | None,
    ) -> None: ...

    def index_transcript_segments(self, job_id: str, segments: list[dict]) -> int: ...
    def index_frame_assets(self, job_id: str, frames: list[dict]) -> int: ...
    def index_ocr_results(self, job_id: str, rows: list[dict]) -> int: ...
    def link_block_sources(self, block_sources: list[dict]) -> None: ...
    def load_blocks_for_job(self, job_id: str) -> list[dict]: ...
    def load_transcript_segments(self, job_id: str) -> list[dict]: ...
    def load_frame_assets(self, job_id: str) -> list[dict]: ...
    def update_block_note_links(self, job_id: str) -> None: ...
    def count_blocks(self, job_id: str) -> int: ...
    def count_blocks_with_sources(self, job_id: str) -> int: ...
    def check_provenance_status(self, job_id: str) -> dict: ...
    def list_indexed_job_ids(self) -> list[str]: ...

