"""Subtitle export helpers for SRT, ASS and timestamped text."""

from __future__ import annotations

import os


def _format_srt(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _format_ass(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    return f"{h}:{m:02d}:{s:02d}.{ms:03d}"


def _format_txt(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    return f"[{h:02d}:{m:02d}:{s:02d}.{ms:03d}]"


def write_srt(segments: list[dict], filepath: str) -> str:
    lines: list[str] = []
    for index, segment in enumerate(segments, start=1):
        lines.append(str(index))
        lines.append(f"{_format_srt(segment['start'])} --> {_format_srt(segment['end'])}")
        lines.append(str(segment["text"]).strip())
        lines.append("")

    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    return filepath


def write_ass(segments: list[dict], filepath: str) -> str:
    header = (
        "[Script Info]\n"
        "; Script generated by video-notes-ai\n"
        "ScriptType: v4.00+\n"
        "PlayResX: 384\n"
        "PlayResY: 288\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        "Style: Default,SimHei,20,&H00FFFFFF,&H000000FF,&H00000000,"
        "&H64000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, "
        "MarginV, Effect, Text\n"
    )

    lines: list[str] = [header]
    for segment in segments:
        text = str(segment["text"]).strip().replace("{", "｛").replace("}", "｝")
        lines.append(
            f"Dialogue: 0,{_format_ass(segment['start'])},"
            f"{_format_ass(segment['end'])},Default,,0,0,0,,{text}"
        )

    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    return filepath


def write_timestamped_txt(segments: list[dict], filepath: str) -> str:
    lines = [
        f"{_format_txt(segment['start'])} → {_format_txt(segment['end'])} "
        f"{str(segment['text']).strip()}"
        for segment in segments
    ]
    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    return filepath
