"""视频/音频下载模块 - 使用 yt-dlp"""

import logging
import os
import glob
import uuid
import time
import shutil
import re
import yt_dlp

from src.infrastructure.video.yt_dlp_compat import apply_yt_dlp_compat

logger = logging.getLogger(__name__)


_BROWSER_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/126.0.0.0 Safari/537.36"
)


def _canonicalize_bilibili_url(url: str) -> str:
    """Return a clean Bilibili video detail URL for yt-dlp.

    Bilibili share/list URLs commonly include tracking query parameters such as
    ``spm_id_from``.  Those parameters should not become part of the task title
    or extractor input.  Keep only the canonical BV/av video id when possible.
    """
    text = (url or "").strip()
    if "bilibili.com" not in text.lower():
        return text

    # /video/BVxxxx or /video/av12345 in either the path or pasted text.
    match = re.search(r"(?i)(BV[0-9A-Za-z]+|av\d+)", text)
    if match:
        video_id = match.group(1)
        return f"https://www.bilibili.com/video/{video_id}"

    return text


def _site_http_headers(url: str) -> dict:
    """Headers required by stricter public-video sites.

    A browser-exported cookies.txt can still fail on Bilibili with HTTP 412 if
    requests do not look like they came from the browser session.  Use the same
    headers for metadata and media downloads that we know work with yt-dlp CLI.
    """
    if "bilibili.com" not in (url or "").lower():
        return {}
    return {
        "http_headers": {
            "User-Agent": _BROWSER_USER_AGENT,
            "Referer": "https://www.bilibili.com/",
            "Origin": "https://www.bilibili.com",
        },
    }


def _cookie_options(cookie_spec: str | None, job_dir: str) -> dict:
    """Return yt-dlp cookie options for login-gated public video sites.

    ``cookie_spec`` may be a path to a Netscape cookies.txt file or a raw
    Cookie header such as ``SESSDATA=...; bili_jct=...``.  Raw cookies are
    converted into a temporary Netscape file inside the per-job temp directory
    so yt-dlp receives them through its normal cookie jar path.
    """
    if not cookie_spec:
        return {}
    text = str(cookie_spec).strip().strip('"')
    if not text:
        return {}

    expanded = os.path.abspath(os.path.expandvars(os.path.expanduser(text)))
    if os.path.isfile(expanded):
        return {"cookiefile": expanded}

    # Raw cookie header pasted from the browser.  Keep this file in the job
    # temp directory and never copy it to final note output.
    if "=" not in text:
        return {}
    cookie_path = os.path.join(job_dir, "cookies.generated.txt")
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Video Notes AI for this local task only.",
    ]
    for item in text.split(';'):
        item = item.strip()
        if not item or '=' not in item:
            continue
        name, value = item.split('=', 1)
        name = name.strip()
        value = value.strip()
        if not name:
            continue
        # Bilibili is the primary login-gated target in the current UI.  A
        # .bilibili.com domain also works for www.bilibili.com video pages.
        lines.append(f".bilibili.com\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
    if len(lines) <= 2:
        return {}
    with open(cookie_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return {"cookiefile": cookie_path}


def _friendly_download_error(url: str, exc: Exception) -> RuntimeError:
    raw = str(exc)
    lower = raw.lower()
    site_hint = ""
    if "bilibili.com" in (url or "").lower():
        site_hint = (
            "\nB站链接请确认：1）使用完整 /video/BV... 或 /video/av... 地址；"
            "2）需要登录、会员、年龄验证、风控或版权限制的视频，需要在设置里填写 cookies.txt；"
            "3）若浏览器里能打开但下载报 412，请使用浏览器式 User-Agent、Referer 和 Origin 请求头；"
            "4）首次验证请先关闭 OCR 与视觉理解。"
        )
    if any(token in lower for token in ("unsupported url", "not a valid url", "no suitable extractor")):
        return RuntimeError(f"在线视频链接无法识别，请粘贴完整视频详情页地址，而不是列表、搜索或截断地址。{site_hint}\nyt-dlp 原始错误：{raw}")
    if any(token in lower for token in ("login", "sign in", "private", "cookie", "403", "401", "412", "precondition")):
        return RuntimeError(f"在线视频下载被站点拒绝，通常需要登录 Cookie 或完整可访问链接。{site_hint}\nyt-dlp 原始错误：{raw}")
    return RuntimeError(f"在线视频下载失败。{site_hint}\nyt-dlp 原始错误：{raw}")


# B站 412 反爬重试配置
_MAX_RETRIES = 3
_RETRY_DELAYS = [2, 5, 10]  # 秒


class DownloadProgressThrottle:
    """yt-dlp 进度节流：每 5% 或每 1 秒最多发送一次更新。"""

    def __init__(self) -> None:
        self._last_percent = -1
        self._last_emit_time = 0.0

    def should_emit(self, percent: float, now: float | None = None) -> bool:
        if now is None:
            now = time.monotonic()
        bucket = int(percent // 5) * 5
        if bucket > self._last_percent:
            self._last_percent = bucket
            self._last_emit_time = now
            return True
        if now - self._last_emit_time >= 1.0:
            self._last_emit_time = now
            return True
        return False

    def mark_finished(self) -> None:
        self._last_percent = 100


_PROGRESS_THROTTLE = DownloadProgressThrottle()


def _make_job_dir(output_dir: str) -> str:
    """在 output_dir 下创建唯一的 per-job 临时子目录，避免并发或同名视频冲突。"""
    job_id = uuid.uuid4().hex[:12]
    job_dir = os.path.join(output_dir, ".dl_tmp", job_id)
    os.makedirs(job_dir, exist_ok=True)
    return job_dir


def download_audio(url: str, output_dir: str = "./output", cookies: str | None = None) -> str:
    """直接下载音频（跳过视频下载和 FFmpeg 提取步骤）

    使用 yt-dlp Python API，不依赖外部命令，
    确保在打包 exe 中也能正常工作。
    每次下载使用独立临时子目录，避免并发或同名视频覆盖。
    """
    os.makedirs(output_dir, exist_ok=True)
    job_dir = _make_job_dir(output_dir)
    url = _canonicalize_bilibili_url(url)
    apply_yt_dlp_compat(url)

    logger.info(f"📥 正在下载音频: {url}")

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": os.path.join(job_dir, "%(id)s-%(title).80s.%(ext)s"),
        "postprocessors": [{
            "key": "FFmpegExtractAudio",
            "preferredcodec": "wav",
        }],
        "quiet": True,
        "no_warnings": True,
    }
    ydl_opts.update(_site_http_headers(url))
    ydl_opts.update(_cookie_options(cookies, job_dir))

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
    except Exception as e:
        shutil.rmtree(job_dir, ignore_errors=True)
        raise _friendly_download_error(url, e)

    # job_dir 是独立目录，直接扫描里面的音频文件
    audio_exts = ('.wav', '.mp3', '.m4a', '.ogg', '.flac')
    audio_files = [
        os.path.join(job_dir, f)
        for f in os.listdir(job_dir)
        if f.lower().endswith(audio_exts)
    ]

    if not audio_files:
        # fallback: 取目录内最新文件
        all_files = [os.path.join(job_dir, f) for f in os.listdir(job_dir)]
        if not all_files:
            shutil.rmtree(job_dir, ignore_errors=True)
            raise RuntimeError("下载完成但未找到音频文件")
        audio_files = all_files

    filepath = max(audio_files, key=os.path.getmtime)
    # 成功后保留在受管理的 .dl_tmp 子目录中，由上层任务统一清理。
    # 不再复制到用户输出根目录，避免大文件污染和额外磁盘 I/O。
    logger.info(f"✅ 音频下载完成: {os.path.basename(filepath)}")
    return filepath


def download_video(url: str, output_dir: str = "./output", cookies: str | None = None) -> str:
    """下载完整视频文件（用于视频截图）。

    当视觉识别启用时调用此函数，获取视频文件后
    可以同时提取音频和关键帧。
    每次下载使用独立临时子目录，避免并发或同名视频覆盖。

    包含 B站 412 反爬重试逻辑。
    """
    os.makedirs(output_dir, exist_ok=True)
    job_dir = _make_job_dir(output_dir)
    url = _canonicalize_bilibili_url(url)
    apply_yt_dlp_compat(url)

    logger.info(f"📥 正在下载视频: {url}")

    ydl_opts = {
        "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "outtmpl": os.path.join(job_dir, "%(id)s-%(title).80s.%(ext)s"),
        "merge_output_format": "mp4",
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
    }
    ydl_opts.update(_site_http_headers(url))
    ydl_opts.update(_cookie_options(cookies, job_dir))

    last_err = None
    for attempt in range(_MAX_RETRIES + 1):
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
            break
        except Exception as e:
            last_err = e
            err_str = str(e)
            # B站 412 反爬 / 临时网络错误 → 重试
            if ("412" in err_str or "Precondition Failed" in err_str) and attempt < _MAX_RETRIES:
                delay = _RETRY_DELAYS[attempt]
                logger.warning(f"⚠️  下载被反爬拦截 (412)，{delay}s 后重试 ({attempt + 1}/{_MAX_RETRIES})…")
                time.sleep(delay)
                continue
            shutil.rmtree(job_dir, ignore_errors=True)
            raise _friendly_download_error(url, e)

    video_exts = ('.mp4', '.mkv', '.webm')
    video_files = [
        os.path.join(job_dir, f)
        for f in os.listdir(job_dir)
        if f.lower().endswith(video_exts)
    ]

    if not video_files:
        all_files = [os.path.join(job_dir, f) for f in os.listdir(job_dir)]
        if not all_files:
            shutil.rmtree(job_dir, ignore_errors=True)
            raise RuntimeError("下载完成但未找到视频文件")
        video_files = all_files

    filepath = max(video_files, key=os.path.getmtime)
    # 成功后保留在受管理的 .dl_tmp 子目录中，由上层任务统一清理。
    # 不再复制到用户输出根目录，避免大文件污染和额外磁盘 I/O。
    logger.info(f"✅ 视频下载完成: {os.path.basename(filepath)}")
    return filepath
