#!/usr/bin/env python3
"""Verify Python/Rust canonicalization and signature interoperability.

Compares VN-C14N-1 canonical JSON bytes and signature payloads generated by
Python and Rust across the entire v0.2 fixture corpus.

Usage:
    python scripts/verify_cross_language_interop.py

Exit code 0: all checks pass.
Exit code 1: mismatch or failure found.
"""
from __future__ import annotations

import base64
import json
import subprocess
import sys
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
import vn_canonical as vnc
from vn_trust import verify_trusted_signature, parse_time

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="backslashreplace")


def hex_str(data: bytes) -> str:
    return data.hex()


def main() -> int:
    failures: list[str] = []

    # ── 1. Golden vectors ────────────────────────────────────────────
    print("═══ Golden vectors ═══")
    vectors_path = REPO_ROOT / "conformance/v0.2/canonicalization-vectors.json"
    vectors = json.loads(vectors_path.read_text("utf-8"))

    for vector in vectors["vectors"]:
        py_bytes = vnc.canonical_bytes(vector["value"])
        py_hex = py_bytes.hex()
        expected = vector["canonical_utf8_hex"]
        if py_hex == expected:
            print(f"  ✅ {vector['name']} — Python matches golden vector")
        else:
            failures.append(f"Golden vector '{vector['name']}': Python mismatch")
            print(f"  ❌ {vector['name']} — Python mismatch")

    sv = vectors["signature_payload_vector"]
    py_sig = vnc.signature_payload(sv["value"], sv["key_id"], sv["signed_at"])
    if py_sig.hex() == sv["payload_hex"]:
        print(f"  ✅ signature_payload — Python matches golden vector")
    else:
        failures.append("Signature payload vector: Python mismatch")
        print(f"  ❌ signature_payload — Python mismatch")

    # ── 2. Compute reference data for Rust comparison ────────────────
    print("\n═══ Reference data for Rust comparison ═══")
    manifest_path = REPO_ROOT / "conformance/v0.2/fixture-manifest.json"
    manifest = json.loads(manifest_path.read_text("utf-8"))

    # Valid fixtures
    all_fixtures = [entry["path"] for entry in manifest["valid"]]
    all_fixtures += [entry["path"] for entry in manifest["invalid"]]

    # Compute Python canonical bytes and record digests
    canonical_digests = {}
    for path in all_fixtures:
        raw = (REPO_ROOT / path).read_text("utf-8")
        value = vnc.strict_loads(raw)
        py_bytes = vnc.canonical_bytes(value)
        canonical_digests[path] = f"sha256:{sha256(py_bytes).hexdigest()}"

    # Compute Python signature payloads for all fixtures
    sig_payload_digests = {}
    for path in all_fixtures:
        raw = (REPO_ROOT / path).read_text("utf-8")
        value = vnc.strict_loads(raw)
        if isinstance(value, dict) and "exchange_manifest" in value:
            unsigned = {k: v for k, v in value.items() if k != "exchange_manifest"}
        else:
            unsigned = value
        manifest_node = value.get("exchange_manifest", {}) if isinstance(value, dict) else {}
        signature = manifest_node.get("signature", {}) if isinstance(manifest_node, dict) else {}
        key_id = signature.get("key_id", "synthetic-fixture-key-v0.2-rc.3")
        signed_at = signature.get("signed_at", "2026-07-12T12:00:00Z")
        try:
            payload = vnc.signature_payload(unsigned, key_id, signed_at)
            sig_payload_digests[path] = f"sha256:{sha256(payload).hexdigest()}"
        except Exception as e:
            sig_payload_digests[path] = f"ERROR: {e}"

    # Write reference data for Rust to read
    reference_path = REPO_ROOT / "conformance/v0.2/cross-language-reference.json"
    reference = {
        "profile": "VN-C14N-1",
        "generated_by": "python",
        "canonical_digests": canonical_digests,
        "signature_payload_digests": sig_payload_digests,
    }
    reference_path.write_text(json.dumps(reference, indent=2, ensure_ascii=False))
    print(f"  ✅ Reference data written to {reference_path.relative_to(REPO_ROOT)}")
    print(f"     Fixtures: {len(canonical_digests)}")

    # ── 3. Trust decision verification ───────────────────────────────
    print("\n═══ Trust decisions (Python) ═══")
    trusted_policy = json.loads(
        (REPO_ROOT / "conformance/v0.2/trust/trusted-policy.json").read_text("utf-8")
    )
    revoked_policy = json.loads(
        (REPO_ROOT / "conformance/v0.2/trust/revoked-policy.json").read_text("utf-8")
    )
    verification_time = datetime(2026, 7, 12, 19, 0, 0, tzinfo=timezone.utc)

    # 3a. Valid bundle with trusted policy → accepted
    valid_path = "examples/v0.2/valid/course-video-complete.json"
    valid_raw = (REPO_ROOT / valid_path).read_text("utf-8")
    valid_value = vnc.strict_loads(valid_raw)
    unsigned_value = {k: v for k, v in valid_value.items() if k != "exchange_manifest"}
    unsigned_canonical = vnc.canonical_bytes(unsigned_value)
    manifest_node = valid_value["exchange_manifest"]
    sig_payload = vnc.signature_payload(
        unsigned_value,
        manifest_node["signature"]["key_id"],
        manifest_node["signature"]["signed_at"],
    )
    trust_errors = verify_trusted_signature(
        manifest_node, unsigned_value, sig_payload,
        trusted_policy, verification_time,
    )
    if not trust_errors:
        print(f"  ✅ Valid bundle with trusted policy — accepted (0 errors)")
    else:
        failures.append(f"Python: valid bundle with trusted policy rejected: {trust_errors}")
        print(f"  ❌ Valid bundle with trusted policy — rejected: {trust_errors}")

    # 3b. Valid bundle without policy → trust error expected
    self_signed_payload = vnc.signature_payload(
        unsigned_value,
        manifest_node["signature"]["key_id"],
        manifest_node["signature"]["signed_at"],
    )
    has_trust_issue = False
    trust_errors_no_policy = verify_trusted_signature(
        manifest_node, unsigned_value, self_signed_payload,
        {}, verification_time,
    )
    if trust_errors_no_policy:
        print(f"  ✅ Valid bundle without policy — trust error (expected)")
    else:
        failures.append("Python: valid bundle without policy not rejected")
        print(f"  ❌ Valid bundle without policy — accepted (expected rejection)")

    # 3c. Revoked key → rejected
    manifest_node3 = valid_value["exchange_manifest"]
    revoked_payload = vnc.signature_payload(
        unsigned_value,
        manifest_node3["signature"]["key_id"],
        manifest_node3["signature"]["signed_at"],
    )
    trust_errors_revoked = verify_trusted_signature(
        manifest_node3, unsigned_value, revoked_payload,
        revoked_policy, verification_time,
    )
    revoke_found = any("revoked" in e.lower() for e in trust_errors_revoked)
    if revoke_found:
        print(f"  ✅ Valid bundle with revoked policy — rejected (expected)")
    else:
        failures.append(f"Python: revoked policy not enforced: {trust_errors_revoked}")
        print(f"  ❌ Valid bundle with revoked policy — not rejected: {trust_errors_revoked}")

    # 3d. Self-signed attacker fixture
    self_signed_raw = (REPO_ROOT / "examples/v0.2/invalid/untrusted-self-signed-key.json").read_text("utf-8")
    ss_value = vnc.strict_loads(self_signed_raw)
    ss_unsigned = {k: v for k, v in ss_value.items() if k != "exchange_manifest"}
    ss_manifest = ss_value["exchange_manifest"]
    ss_payload = vnc.signature_payload(
        ss_unsigned,
        ss_manifest["signature"]["key_id"],
        ss_manifest["signature"]["signed_at"],
    )
    ss_errors = verify_trusted_signature(
        ss_manifest, ss_unsigned, ss_payload,
        trusted_policy, verification_time,
    )
    untrusted_found = any("not trusted" in e.lower() or "untrusted" in e.lower() for e in ss_errors)
    if untrusted_found:
        print(f"  ✅ Self-signed attacker fixture — rejected (expected)")
    else:
        failures.append(f"Python: self-signed key not rejected: {ss_errors}")
        print(f"  ❌ Self-signed attacker fixture — not rejected: {ss_errors}")

    # ── Summary ──────────────────────────────────────────────────────
    print(f"\n═══════════════════════════════════════════")
    if failures:
        print(f"  ❌ {len(failures)} failure(s)")
        for f in failures:
            print(f"    • {f}")
        return 1
    else:
        print(f"  ✅ All Python-side checks passed")
        print(f"  ✅ Reference data written for Rust comparison")
        return 0


if __name__ == "__main__":
    sys.exit(main())
